on:
  workflow_dispatch:

jobs:
  job1: 
    runs-on: ubuntu-22.04

    steps:
      - name: echooing
        run: echo "hi imm surendra"
      - name: 
        run: mkdir surendra

      - name: 
        run: ls
  
  job2:

    runs-on: ubuntu-22.04

    steps:
      - name: display
        run: ls